# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170329_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(null=True)),
                ('mazes_evaluated', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='owner',
        ),
    ]
